package Server.enumeration;

/**
 * Created by tearsyu on 18/05/17.
 */
public enum EnumService {
    AUTH, PIECE, INDICATOR, SAVEVEHICLE, BREAKDOWNLOAD, PARKINGDOWLOAD, VEHICLEDOWNLOAD,
    SEARCHVEHICLE,SEARCHInfoVEHICLE,VEHICLERELOCATE,TABLE,IMPORT_PIECE,AFFICHE_PSORT,FIN,GET_OPERATION_SORT,SHOW_INFO,ADD_OP,FINIR

}
