package Client.enumeration;

/**
 * Created by tearsyu on 18/05/17.
 */
public enum EnumService {
    AUTH, PIECE, INDICATOR, SAVEVEHICLE, BREAKDOWNLOAD, PARKINGDOWLOAD, VEHICLEDOWNLOAD, 
    SEARCHVEHICLE,SEARCHInfoVEHICLE,VEHICLERELOCATE,TABLE, AFFICHE_PSORT, ADD_OP, SHOW_INFO, GET_OPERATION_SORT
    ,IMPORT_PIECE,FIN,FINIR

}
